name: library_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  url_launcher: ^6.3.1
  intl: ^0.18.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Path to your icon file
  adaptive_icon_background: "#FFFFFF" # For Android adaptive icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding.png
    - assets/google.png
    - assets/defaultItemPic.png
